spring:
  datasource:
    todos:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
    topics:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: true
